export const TEST_USER_ID = "user123";
export const TEST_RESET_TIME = 123456789;
export const TEST_CURRENT_LIMIT = 100;
export const TEST_REQUESTS_UNDER_LIMIT = 1;
export const TEST_REMAINING_REQUESTS_UNDER_LIMIT =
	TEST_CURRENT_LIMIT - TEST_REQUESTS_UNDER_LIMIT;
export const TEST_REMAINING_REQUESTS_ZERO = 0;
